server:
  port: 8081 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: query_builder # 服务名
  datasource: # mysql数据库连接
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/query_builder?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:/com/example/query_builder/mapper/xml/*.xml